In [36]:
import numpy as np

np.__version__

'1.19.5'

In [37]:
np.zeros(2)

array([0., 0.])

In [38]:
np.ones(3)

array([1., 1., 1.])

In [39]:
np.empty(1) 

array([1.])

In [40]:
np.array([1,5])

array([1, 5])

In [41]:
a = np.array([[1, 2, 3, 4, 5],
              [4, 5, 6, 7, 8]])
a

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [42]:
a.flat[:]


array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [43]:
a.flat[6]

5